In [1]:
import numpy as np

In [8]:
a=np.array(42)
print(a)
print(type(a))

42
<class 'numpy.ndarray'>


In [10]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [14]:
c=np.array([[[1,2],[3,4],[5,6]]])
print(c)
print(c.ndim)


[[[1 2]
  [3 4]
  [5 6]]]
3


In [15]:
d=np.array([1,2,3,4,5],ndmin=5)
print(d)

[[[[[1 2 3 4 5]]]]]
